/*
Token Tracker Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokentracker

import (
	"encoding/json"
)

// checks if the TokenTrackerAdjustTokenBalanceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenTrackerAdjustTokenBalanceRequest{}

// TokenTrackerAdjustTokenBalanceRequest struct for TokenTrackerAdjustTokenBalanceRequest
type TokenTrackerAdjustTokenBalanceRequest struct {
	Amount *string `json:"amount,omitempty"`
}

// NewTokenTrackerAdjustTokenBalanceRequest instantiates a new TokenTrackerAdjustTokenBalanceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenTrackerAdjustTokenBalanceRequest() *TokenTrackerAdjustTokenBalanceRequest {
	this := TokenTrackerAdjustTokenBalanceRequest{}
	return &this
}

// NewTokenTrackerAdjustTokenBalanceRequestWithDefaults instantiates a new TokenTrackerAdjustTokenBalanceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenTrackerAdjustTokenBalanceRequestWithDefaults() *TokenTrackerAdjustTokenBalanceRequest {
	this := TokenTrackerAdjustTokenBalanceRequest{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *TokenTrackerAdjustTokenBalanceRequest) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenTrackerAdjustTokenBalanceRequest) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// IsSetAmount returns a boolean if a field has been set.
func (o *TokenTrackerAdjustTokenBalanceRequest) IsSetAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *TokenTrackerAdjustTokenBalanceRequest) SetAmount(v string) {
	o.Amount = &v
}

func (o TokenTrackerAdjustTokenBalanceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenTrackerAdjustTokenBalanceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	return toSerialize, nil
}

type NullableTokenTrackerAdjustTokenBalanceRequest struct {
	value *TokenTrackerAdjustTokenBalanceRequest
	isSet bool
}

func (v NullableTokenTrackerAdjustTokenBalanceRequest) Get() *TokenTrackerAdjustTokenBalanceRequest {
	return v.value
}

func (v *NullableTokenTrackerAdjustTokenBalanceRequest) Set(val *TokenTrackerAdjustTokenBalanceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenTrackerAdjustTokenBalanceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenTrackerAdjustTokenBalanceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenTrackerAdjustTokenBalanceRequest(val *TokenTrackerAdjustTokenBalanceRequest) *NullableTokenTrackerAdjustTokenBalanceRequest {
	return &NullableTokenTrackerAdjustTokenBalanceRequest{value: val, isSet: true}
}

func (v NullableTokenTrackerAdjustTokenBalanceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenTrackerAdjustTokenBalanceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


