/*
Token Tracker Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokentracker

import (
	"encoding/json"
)

// checks if the TokentrackerStripeWebhookRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokentrackerStripeWebhookRequest{}

// TokentrackerStripeWebhookRequest struct for TokentrackerStripeWebhookRequest
type TokentrackerStripeWebhookRequest struct {
	Data *StripeEventData `json:"data,omitempty"`
	Account *string `json:"account,omitempty"`
	ApiVersion *string `json:"apiVersion,omitempty"`
	Created *string `json:"created,omitempty"`
	Id *string `json:"id,omitempty"`
	Livemode *bool `json:"livemode,omitempty"`
	Object *string `json:"object,omitempty"`
	PendingWebhooks *string `json:"pendingWebhooks,omitempty"`
	Request *StripeEventRequest `json:"request,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewTokentrackerStripeWebhookRequest instantiates a new TokentrackerStripeWebhookRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokentrackerStripeWebhookRequest() *TokentrackerStripeWebhookRequest {
	this := TokentrackerStripeWebhookRequest{}
	return &this
}

// NewTokentrackerStripeWebhookRequestWithDefaults instantiates a new TokentrackerStripeWebhookRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokentrackerStripeWebhookRequestWithDefaults() *TokentrackerStripeWebhookRequest {
	this := TokentrackerStripeWebhookRequest{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TokentrackerStripeWebhookRequest) GetData() StripeEventData {
	if o == nil || IsNil(o.Data) {
		var ret StripeEventData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokentrackerStripeWebhookRequest) GetDataOk() (*StripeEventData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// IsSetData returns a boolean if a field has been set.
func (o *TokentrackerStripeWebhookRequest) IsSetData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given StripeEventData and assigns it to the Data field.
func (o *TokentrackerStripeWebhookRequest) SetData(v StripeEventData) {
	o.Data = &v
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *TokentrackerStripeWebhookRequest) GetAccount() string {
	if o == nil || IsNil(o.Account) {
		var ret string
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokentrackerStripeWebhookRequest) GetAccountOk() (*string, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// IsSetAccount returns a boolean if a field has been set.
func (o *TokentrackerStripeWebhookRequest) IsSetAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given string and assigns it to the Account field.
func (o *TokentrackerStripeWebhookRequest) SetAccount(v string) {
	o.Account = &v
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *TokentrackerStripeWebhookRequest) GetApiVersion() string {
	if o == nil || IsNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokentrackerStripeWebhookRequest) GetApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// IsSetApiVersion returns a boolean if a field has been set.
func (o *TokentrackerStripeWebhookRequest) IsSetApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *TokentrackerStripeWebhookRequest) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *TokentrackerStripeWebhookRequest) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokentrackerStripeWebhookRequest) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// IsSetCreated returns a boolean if a field has been set.
func (o *TokentrackerStripeWebhookRequest) IsSetCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *TokentrackerStripeWebhookRequest) SetCreated(v string) {
	o.Created = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TokentrackerStripeWebhookRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokentrackerStripeWebhookRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *TokentrackerStripeWebhookRequest) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TokentrackerStripeWebhookRequest) SetId(v string) {
	o.Id = &v
}

// GetLivemode returns the Livemode field value if set, zero value otherwise.
func (o *TokentrackerStripeWebhookRequest) GetLivemode() bool {
	if o == nil || IsNil(o.Livemode) {
		var ret bool
		return ret
	}
	return *o.Livemode
}

// GetLivemodeOk returns a tuple with the Livemode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokentrackerStripeWebhookRequest) GetLivemodeOk() (*bool, bool) {
	if o == nil || IsNil(o.Livemode) {
		return nil, false
	}
	return o.Livemode, true
}

// IsSetLivemode returns a boolean if a field has been set.
func (o *TokentrackerStripeWebhookRequest) IsSetLivemode() bool {
	if o != nil && !IsNil(o.Livemode) {
		return true
	}

	return false
}

// SetLivemode gets a reference to the given bool and assigns it to the Livemode field.
func (o *TokentrackerStripeWebhookRequest) SetLivemode(v bool) {
	o.Livemode = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *TokentrackerStripeWebhookRequest) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokentrackerStripeWebhookRequest) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// IsSetObject returns a boolean if a field has been set.
func (o *TokentrackerStripeWebhookRequest) IsSetObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *TokentrackerStripeWebhookRequest) SetObject(v string) {
	o.Object = &v
}

// GetPendingWebhooks returns the PendingWebhooks field value if set, zero value otherwise.
func (o *TokentrackerStripeWebhookRequest) GetPendingWebhooks() string {
	if o == nil || IsNil(o.PendingWebhooks) {
		var ret string
		return ret
	}
	return *o.PendingWebhooks
}

// GetPendingWebhooksOk returns a tuple with the PendingWebhooks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokentrackerStripeWebhookRequest) GetPendingWebhooksOk() (*string, bool) {
	if o == nil || IsNil(o.PendingWebhooks) {
		return nil, false
	}
	return o.PendingWebhooks, true
}

// IsSetPendingWebhooks returns a boolean if a field has been set.
func (o *TokentrackerStripeWebhookRequest) IsSetPendingWebhooks() bool {
	if o != nil && !IsNil(o.PendingWebhooks) {
		return true
	}

	return false
}

// SetPendingWebhooks gets a reference to the given string and assigns it to the PendingWebhooks field.
func (o *TokentrackerStripeWebhookRequest) SetPendingWebhooks(v string) {
	o.PendingWebhooks = &v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *TokentrackerStripeWebhookRequest) GetRequest() StripeEventRequest {
	if o == nil || IsNil(o.Request) {
		var ret StripeEventRequest
		return ret
	}
	return *o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokentrackerStripeWebhookRequest) GetRequestOk() (*StripeEventRequest, bool) {
	if o == nil || IsNil(o.Request) {
		return nil, false
	}
	return o.Request, true
}

// IsSetRequest returns a boolean if a field has been set.
func (o *TokentrackerStripeWebhookRequest) IsSetRequest() bool {
	if o != nil && !IsNil(o.Request) {
		return true
	}

	return false
}

// SetRequest gets a reference to the given StripeEventRequest and assigns it to the Request field.
func (o *TokentrackerStripeWebhookRequest) SetRequest(v StripeEventRequest) {
	o.Request = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TokentrackerStripeWebhookRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokentrackerStripeWebhookRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// IsSetType returns a boolean if a field has been set.
func (o *TokentrackerStripeWebhookRequest) IsSetType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TokentrackerStripeWebhookRequest) SetType(v string) {
	o.Type = &v
}

func (o TokentrackerStripeWebhookRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokentrackerStripeWebhookRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.ApiVersion) {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Livemode) {
		toSerialize["livemode"] = o.Livemode
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.PendingWebhooks) {
		toSerialize["pendingWebhooks"] = o.PendingWebhooks
	}
	if !IsNil(o.Request) {
		toSerialize["request"] = o.Request
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableTokentrackerStripeWebhookRequest struct {
	value *TokentrackerStripeWebhookRequest
	isSet bool
}

func (v NullableTokentrackerStripeWebhookRequest) Get() *TokentrackerStripeWebhookRequest {
	return v.value
}

func (v *NullableTokentrackerStripeWebhookRequest) Set(val *TokentrackerStripeWebhookRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTokentrackerStripeWebhookRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTokentrackerStripeWebhookRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokentrackerStripeWebhookRequest(val *TokentrackerStripeWebhookRequest) *NullableTokentrackerStripeWebhookRequest {
	return &NullableTokentrackerStripeWebhookRequest{value: val, isSet: true}
}

func (v NullableTokentrackerStripeWebhookRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokentrackerStripeWebhookRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


